"""Writes the full 80-friend loop script (step 6.8) to stdout.
New game; 20 containers in each area in play order (the gate scenes play
after the 10th friend of the meadow, woods and shore); the way on at the
end of each area; the whole shelf; Momo's bed. Every fourth container is
left to open itself and every fourth friend leaves on its own."""
EXITS = {0: (470, 200), 1: (472, 120), 2: (474, 150)}     # the way on, east (see tools/areas.py)
out = ['# Full 80-friend loop (generated by make_full_loop.py)', 'wait 20', 'tap A', 'wait 15', 'tap A', 'wait 25']
n = 0
for area in range(4):
    out.append(f'# ---- area {area}')
    for k in range(20):
        n += 1
        out.append(f'# friend {n}')
        out.append('seek 4000')
        if k == 0:
            out.append(f'shot full_a{area}_first')
        out.append('tap A')
        if n % 4 == 3:                         # nobody presses: it opens by itself
            out += ['wait 520']
        else:
            out += ['wait 50', 'tap A', 'wait 29', 'tap B', 'wait 31', 'tap A', 'wait 140']
        if n % 4 == 1:                         # nobody squishes: the friend leaves on its own
            out += ['wait 360']
        else:
            out += ['tap A', 'wait 20', 'tap B', 'wait 20', 'tap A', 'wait 110']
    out += ['wait 30', f'shot full_a{area}_done', 'wait 420']      # the full page's parade (step 7.3) plays out
    if area in EXITS:
        x, y = EXITS[area]
        out += [f'walkto {x} {y} 3000', 'wait 40']
out += ['hold START 1', 'wait 40', 'shot full_shelf3', 'tap L', 'wait 20', 'shot full_shelf2', 'tap L', 'wait 20',
        'shot full_shelf1', 'tap L', 'wait 20', 'shot full_shelf0', 'tap B', 'wait 40',
        'walkto 416 110 3000', 'wait 40', 'shot full_momo_home', 'walkto 330 150 2000', 'wait 60', 'shot full_pen_clouds',
        'tap B', 'wait 5', 'shot full_hop', 'wait 90']
print('\n'.join(out))
