"""Songs for the GBA PSG, written with note names.

Each song has two voices: a lead on the wave channel (3) and a bass on
square channel 2. Time is counted in ticks; `tick` is frames per tick
(60 frames = 1 second), and a tick is normally a sixteenth note.

Voice text: tokens separated by spaces. "C5:4" is C in octave 5 for 4
ticks, "r:2" is a rest, "Bb3" or "F#4" use flats and sharps. A token
without ":n" keeps the length of the one before it. "|" (bar line) is
ignored, it only helps reading. Both voices of a song must have the same
length in ticks, so they stay together when the song loops.

Usage: python3 music.py OUTDIR  (writes music_data.c/.h and music_songs.json)
"""
import json
import os
import sys


NOTE = {'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11}
CPU_HZ = 16777216

# wave shapes for the lead: 32 samples, 0..15, made from a few harmonics
def _wave(harmonics):
    import math
    v = [sum(a * math.sin(2 * math.pi * k * i / 32 + ph) for k, a, ph in harmonics) for i in range(32)]
    lo, hi = min(v), max(v)
    return [round((x - lo) / (hi - lo) * 15) for x in v]


WAVES = {
    'sine': _wave([(1, 1.0, 0)]),                              # pure and soft (the old melody wave)
    'bell': _wave([(1, 1.0, 0), (2, 0.45, 0), (3, 0.12, 0)]),   # music box: brighter, round
    'hollow': _wave([(1, 1.0, 0), (3, 0.30, 0)]),              # flute-like, a little woody
}


def midi(name):
    """'C4' -> 60, 'F#5' -> 78, 'Bb3' -> 58."""
    n = NOTE[name[0].upper()]
    rest = name[1:]
    while rest and rest[0] in '#b':
        n += 1 if rest[0] == '#' else -1
        rest = rest[1:]
    return n + 12 * (int(rest) + 1)


def hz(m):
    return 440.0 * 2 ** ((m - 69) / 12)


def parse(text):
    """Voice text -> list of (midi or 0, ticks)."""
    out, length = [], 4
    for tok in text.split():
        if tok == '|':
            continue
        name, _, ln = tok.partition(':')
        if ln:
            length = int(ln)
        if not 1 <= length <= 255:
            raise ValueError(f'bad length in {tok!r}')
        out.append((0 if name == 'r' else midi(name), length))
    return out


SONGS = {}


def song(key, title, tick, lead, bass, loop=True, wave='sine', lead_level=0, lead_decay=0,
         lead_gap=1, bass_vol=6, bass_duty=1, bass_step=3, bass_gap=1):
    """lead_level: 0 = 100%, 1 = 75%, 2 = 50%, 3 = 25% wave volume.
    lead_decay: frames per step down (toward 25%), 0 = hold.
    *_gap: silent frames at the end of each note (detached notes).
    bass_vol, bass_step: square envelope start (0..15) and fade step (0 = hold).
    bass_duty: 0 = 12.5%, 1 = 25%, 2 = 50%."""
    SONGS[key] = dict(title=title, tick=tick, lead=parse(lead), bass=parse(bass), loop=loop, wave=wave,
                      lead_level=lead_level, lead_decay=lead_decay, lead_gap=lead_gap,
                      bass_vol=bass_vol, bass_duty=bass_duty, bass_step=bass_step, bass_gap=bass_gap)


# ---------------------------------------------------------------- songs
# Engine test: a C major scale up and down over a C / G bass, 2 bars of
# 16 ticks at 8 frames per tick (112 bpm in quarter notes).
song('scale', 'Scale test', 8,
     lead='C5:2 D5 E5 F5 G5 A5 B5 C6 | C6 B5 A5 G5 F5 E5 D5 C5',
     bass='C3:8 G2 | G2 C3',
     lead_level=1, lead_decay=0, bass_vol=6, bass_step=0)


# ---------------------------------------------------------------- export
def sq_rate(f):
    return 2048 - round(CPU_HZ / 128 / f)


def wave_rate(f):
    return 2048 - round(CPU_HZ / 256 / f)


def check_rates():
    """Every note used must land within 12 cents of its true pitch."""
    import math
    used = {m for s in SONGS.values() for v in ('lead', 'bass') for m, _ in s[v] if m}
    for key, s in SONGS.items():
        for v, fn, div in (('lead', wave_rate, 256), ('bass', sq_rate, 128)):
            for m, _ in s[v]:
                if not m:
                    continue
                r = fn(hz(m))
                if not 0 <= r < 2048:
                    raise ValueError(f'{key} {v}: note {m} out of range')
                real = CPU_HZ / div / (2048 - r)
                cents = 1200 * math.log2(real / hz(m))
                if abs(cents) > 12:
                    raise ValueError(f'{key} {v}: note {m} is {cents:.1f} cents off')
    return used


def export(outdir):
    check_rates()
    for key, s in SONGS.items():
        tl, tb = sum(n for _, n in s['lead']), sum(n for _, n in s['bass'])
        if tl != tb:
            raise ValueError(f'{key}: lead is {tl} ticks, bass is {tb}')
    c = ['/* Generated by tools/music.py. Do not edit. */', '#include "music_data.h"', '']
    h = ['/* Generated by tools/music.py. Do not edit. */', '#ifndef MUSIC_DATA_H', '#define MUSIC_DATA_H',
         '#include "sound.h"', '']

    def arr(ctype, ident, values, per=12, fmt='{}'):
        body = ',\n'.join('    ' + ', '.join(fmt.format(v) for v in values[i:i + per])
                          for i in range(0, len(values), per))
        c.append(f'const {ctype} {ident}[{len(values)}] __attribute__((aligned(4))) = {{\n{body}\n}};')
        h.append(f'extern const {ctype} {ident}[{len(values)}];')

    arr('u16', 'music_sq_rate', [sq_rate(hz(m)) if m >= 36 else 0 for m in range(128)], fmt='{:4d}')
    arr('u16', 'music_wave_rate', [wave_rate(hz(m)) if m >= 24 else 0 for m in range(128)], fmt='{:4d}')
    for name, w in WAVES.items():
        words = []
        for i in range(0, 32, 8):          # wave RAM: 2 samples per byte, the high nibble plays first
            v = 0
            for j in range(4):
                v |= ((w[i + 2 * j] << 4) | w[i + 2 * j + 1]) << (8 * j)
            words.append(v)
        arr('u32', f'music_wave_{name}', words, fmt='0x{:08X}')
    for key, sg in SONGS.items():
        for v in ('lead', 'bass'):
            data = []
            for m, n in sg[v]:
                data += [m, n]
            arr('u8', f'song_{key}_{v}', data, per=16)
    for i, key in enumerate(SONGS):
        h.append(f'#define SONG_{key.upper()} {i}')
    h.append(f'#define SONG_COUNT {len(SONGS)}')
    h.append('extern const Song songs[SONG_COUNT];')
    c.append('const Song songs[SONG_COUNT] = {')
    for key, sg in SONGS.items():
        c.append(f'    {{"{sg["title"]}", song_{key}_lead, song_{key}_bass, {len(sg["lead"])}, {len(sg["bass"])},\n'
                 f'     music_wave_{sg["wave"]}, {sg["tick"]}, {int(sg["loop"])}, {sg["lead_level"]}, '
                 f'{sg["lead_decay"]}, {sg["lead_gap"]}, {sg["bass_vol"]}, {sg["bass_duty"]}, '
                 f'{sg["bass_step"]}, {sg["bass_gap"]}}},')
    c.append('};')
    h += ['', '#endif']
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, 'music_data.c'), 'w') as f:
        f.write('\n'.join(c) + '\n')
    with open(os.path.join(outdir, 'music_data.h'), 'w') as f:
        f.write('\n'.join(h) + '\n')
    with open(os.path.join(outdir, 'music_songs.json'), 'w') as f:
        json.dump({k: dict(s, index=i) for i, (k, s) in enumerate(SONGS.items())}, f, indent=1)


if __name__ == '__main__':
    export(sys.argv[1] if len(sys.argv) > 1 else 'build')
